services:
  db:
    build: .
    environment:
    - MONGO_INITDB_ROOT_USERNAME=tcmb
    - MONGO_INITDB_ROOT_PASSWORD=tcmb-mdp!
    container_name: mongodb
    ports:
    - "28648:27017"
  
  redis:
    image: redis:latest
    container_name: redisdb
    ports:
    - "6379:6379"

  nodejs:
    build: 
      context: ../api
    container_name: nodejs_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ../web:/app/public
    command: npm start
    depends_on:
      - db
      - redis

