services:
  db:
    image: mongo:latest
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=password
    container_name: mongodb
    ports:
    - "27017:27017"
  
  redis:
    image: redis:latest
    ports:
    - "6379:6379"

  nodejs:
    build: .
    container_name: nodejs_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: npm start
    depends_on:
      - db
      - redis

